openapi: 3.0.0
info:
  version: 1.0.0
  title: Products - POC
  description: >
    A draft API resource model for products proof of concept based on Medicare
    Products and Plans
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/RAJESHP1231234_1/Rajesh/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/Enterprise-API/Producs-POC/1.0.0'
  - url: 'https://api.humana.com/v1'
    #description: The server URL for v1 APIs
paths:
  /lookups/plan-service-area-codes:
    get:
      tags:
        - Lookups
      summary: Searchable list of plan service areas (FIPS code)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lookups-plan-service-area-codes-response'
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP-401'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP-404'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP-500'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP-503'
components:
  schemas:
    lookups-plan-service-area-codes-response:
      allOf:
        - $ref: '#/components/schemas/lookups-plan-service-area-codes-block'
    lookups-plan-service-area-codes-block:
      properties:
        serviceAreaCodes:
          type: array
          description: List of service area codes
          items:
            properties:
              fipsCode:
                type: string
                description: Plan FIPS code
                example: 21111
              label:
                type: string
                description: Human-readable label for the code
                example: Plan FIPS Code
              description:
                type: string
                description: Plan FIPS Code
                example: Plan FIPS Code
              postalCodes:
                type: string
                description: List of postal codes applicable to the FIPS code
                example:
                  - '22111'
                  - '11111'
              state:
                type: string
                description: Plan service area state
                example: KY
              county:
                type: string
                description: Plan service area county
                example: Jefferson
    HTTP-401:
      properties:
        timestamp:
          type: string
          description: An ISO 8601 date/time in UTC indicating when the error occurred
          example: '2022-02-15T22:14:45.624+0000'
        status:
          type: integer
          description: >-
            The HTTP status code generated by service for this occurrence of the
            problem.
          example: 401
        code:
          type: string
          description: A case-insensitive alpha-numeric identifier for the error.
          example: invalid.login
        path:
          type: string
          description: >-
            A URI reference that identifies the Enterprise API resource which
            produced the problem.
          example: v1/products/12345/plans
    HTTP-404:
      properties:
        timestamp:
          type: string
          description: An ISO 8601 date/time in UTC indicating when the error occurred
          example: '2022-02-15T22:14:45.624+0000'
        status:
          type: integer
          description: >-
            The HTTP status code generated by service for this occurrence of the
            problem.
          example: 404
        code:
          type: string
          description: A case-insensitive alpha-numeric identifier for the error.
          example: resource.not.found
        path:
          type: string
          description: >-
            A URI reference that identifies the Enterprise API resource which
            produced the problem.
          example: v1/products/A1
    HTTP-422:
      properties:
        timestamp:
          type: string
          description: An ISO 8601 date/time in UTC indicating when the error occurred
          example: '2022-02-15T22:14:45.624+0000'
        status:
          type: integer
          description: >-
            The HTTP status code generated by service for this occurrence of the
            problem.
          example: 422
        code:
          type: string
          description: >-
            A case-insensitive alpha-numeric identifier for the error. The
            collection of expected error codes should be documented within the
            OpenAPI specification.
          example: P5ABCD
        path:
          type: string
          description: >-
            A URI reference that identifies the Enterprise API resource which
            produced the problem.
          example: v1/products/search
        correlationId:
          type: string
          description: >-
            a trace identifier which may be used to consult logs and telemetry
            infrastructure regarding the error
          example: 1234HH4445
        causes:
          type: array
          items:
            properties:
              timestamp:
                type: string
                description: >-
                  An ISO 8601 date/time in UTC indicating when the error
                  occurred
                example: '2022-02-15T22:14:45.624+0000'
              status:
                type: integer
                description: >-
                  The HTTP status code generated by service for this occurrence
                  of the problem.
                example: 422
              code:
                type: string
                description: >-
                  A case-insensitive alpha-numeric identifier for the error. The
                  collection of expected error codes should be documented within
                  the OpenAPI specification.
                example: P5ABCD
              path:
                type: string
                description: >-
                  A URI reference that identifies the Enterprise API resource
                  which produced the problem.
                example: v1/products/12345/plans
              correlationId:
                type: string
                description: >-
                  a trace identifier which may be used to consult logs and
                  telemetry infrastructure regarding the error
                example: 1234HH4445
    HTTP-500:
      properties:
        timestamp:
          type: string
          description: An ISO 8601 date/time in UTC indicating when the error occurred
          example: '2022-02-15T22:14:45.624+0000'
        status:
          type: integer
          description: >-
            The HTTP status code generated by service for this occurrence of the
            problem.
          example: 500
        code:
          type: string
          description: >-
            A case-insensitive alpha-numeric identifier for the error. The
            collection of expected error codes should be documented within the
            OpenAPI specification.
          example: AABBCC
        path:
          type: string
          description: >-
            A URI reference that identifies the Enterprise API resource which
            produced the problem.
          example: v1/products/search
        correlationId:
          type: string
          description: >-
            a trace identifier which may be used to consult logs and telemetry
            infrastructure regarding the error
          example: 1234HH4445
        causes:
          type: array
          items:
            properties:
              timestamp:
                type: string
                description: >-
                  An ISO 8601 date/time in UTC indicating when the error
                  occurred
                example: '2022-02-15T22:14:45.624+0000'
              status:
                type: integer
                description: >-
                  The HTTP status code generated by service for this occurrence
                  of the problem.
                example: 500
              code:
                type: string
                description: >-
                  A case-insensitive alpha-numeric identifier for the error. The
                  collection of expected error codes should be documented within
                  the OpenAPI specification.
                example: AABBDD
              path:
                type: string
                description: >-
                  A URI reference that identifies the Enterprise API resource
                  which produced the problem.
                example: v1/products/search
              correlationId:
                type: string
                description: >-
                  a trace identifier which may be used to consult logs and
                  telemetry infrastructure regarding the error
                example: 1234HH4445
    HTTP-503:
      properties:
        timestamp:
          type: string
          description: An ISO 8601 date/time in UTC indicating when the error occurred
          example: '2022-02-15T22:14:45.624+0000'
        status:
          type: integer
          description: >-
            The HTTP status code generated by service for this occurrence of the
            problem.
          example: 503
        code:
          type: string
          description: >-
            A case-insensitive alpha-numeric identifier for the error. The
            collection of expected error codes should be documented within the
            OpenAPI specification.
          example: AABBCC
        path:
          type: string
          description: >-
            A URI reference that identifies the Enterprise API resource which
            produced the problem.
          example: v1/products/12345
        correlationId:
          type: string
          description: >-
            a trace identifier which may be used to consult logs and telemetry
            infrastructure regarding the error
          example: 1234HH4445
        causes:
          type: array
          items:
            properties:
              timestamp:
                type: string
                description: >-
                  An ISO 8601 date/time in UTC indicating when the error
                  occurred
                example: '2022-02-15T22:14:45.624+0000'
              status:
                type: integer
                description: >-
                  The HTTP status code generated by service for this occurrence
                  of the problem.
                example: 503
              code:
                type: string
                description: >-
                  A case-insensitive alpha-numeric identifier for the error. The
                  collection of expected error codes should be documented within
                  the OpenAPI specification.
                example: AABBDD
              path:
                type: string
                description: >-
                  A URI reference that identifies the Enterprise API resource
                  which produced the problem.
                example: v1/products/12345
              correlationId:
                type: string
                description: >-
                  a trace identifier which may be used to consult logs and
                  telemetry infrastructure regarding the error
                example: 1234HH4445
