name: SwaggerHub Integration

on:
  workflow_dispatch:
  push:

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: |
            /root/.cache
            /root/.local/share/Super-Linter
          key: ${{ runner.os }}

      - name: Lint Code Base
        uses: prathira/super-linter@latest
        id: lintcode
        env:
          VALIDATE_OPENAPI: true
          DEFAULT_BRANCH: swagger-sync
          CREATE_LOG_FILE: true
          LOG_FILE: linter.log
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPER_LINTER_USE_CACHE: true
          SUPER_LINTER_CACHE_PATH: /root/.cache/Super-Linter
