name: Lint OpenAPI Specification
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Spectral
        run: npm install -g @stoplight/spectral
      - name: Lint OpenAPI Specification
        run: spectral lint openapi/Enterprise-API-Providers_Practitioner-1-swagger.yaml -r .github/linters/.openapirc.yml
