name: OpenAPI Linting

on:
  push:
    branches:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Super Linter dependencies
        uses: actions/cache@v2
        with:
          path: ~/.super-linter
          key: ${{ runner.os }}-super-linter-${{ hashFiles('**/*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-super-linter-

      - name: Install dependencies
        run: |
          cd /root/.super-linter
          npm install

      - name: Lint OpenAPI spec
        uses: github/super-linter@v4
        with:
          args: openapi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
