name: SwaggerHub Integration
on: workflow_dispatch
jobs:
  Hello:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        id: lintcode
        env:
          VALIDATE_OPENAPI: true
          DEFAULT_BRANCH: swaggerhub
          CREATE_LOG_FILE: true
          LOG_FILE: linter.log
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List files
        id: lintOutput
        if: failure() && steps.lintcode.outcome == 'failure'
        run: |
          ERROR_REGEX='^(\s)*(\d)*:(\d)*\serror\s.*$'
          grep -Eoh "$ERROR_REGEX" linter.log
      - name: Update swagerHub
        if: failure() && steps.lintcode.outcome == 'failure'
        run: |
         ERROR_MSG=$(cat error.log)
         #request_payload={\"body\":\"$ERROR_MSG\"}
         #echo "${ERROR_MSG}"
         sh ./.github/scripts/apicall.sh
        shell: bash
