name: GitHub Super Linter
on:
  push:
    branches: [ test ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Super Linter
      uses: github/super-linter-action@v4.1.0
      with:
        VALIDATE_ALL_CODEBASE: true
      env:
        VALIDATE_ALL_CODEBASE: true
