name: SwaggerHub Integration
on: workflow_dispatch
jobs:
  Hello:
   runs-on: ubuntu-latest
   steps:
      
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: /usr/bin/docker
          key: ${{ runner.os }}
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List Files
        run: |
          cd /github/workspace
          ls -a
      
      - name: Lint Code Base
        uses: github/super-linter@v4
        id: lintcode
        env:
          VALIDATE_OPENAPI: true
          DEFAULT_BRANCH: main
          CREATE_LOG_FILE: true
          LOG_FILE: linter.log
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract error logs
        id: extractErrors
        if: failure() && steps.lintcode.outcome == 'failure'
        run: |
          ERROR_REGEX='^\s*([0-9]*):([0-9]*)\s*error\s*.*$'
          # Extracting only errors from log file
          grep -Eoh "$ERROR_REGEX" linter.log > error1.log
          # Removing double quotes
          sed -i 's#"##g' error1.log
          # Removing duplicate entries in error log file
          awk -i inplace '!seen[$0]++' error1.log
          #ERROR_MESSAGE1=$(sed -i ':a;N;$!ba;s/\n/ /g' error.log)
          cat error1.log | while read line; do echo "<td>"${line}"</td>" >> error.log; done
      - name: Update swagerHub
        if: failure() && steps.lintcode.outcome == 'failure'
        run: |
         sh ./.github/scripts/apicall.sh "${{steps.lintcode.outcome}}"
        shell: bash
