name: Cache httpd Docker Image

on:
  push:
    branches:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build and tag Docker image
      run: docker build -t my-httpd-image .

    - name: Cache Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        cache-from: type=local,src=my-httpd-image
        cache-to: type=local,dest=my-httpd-image-cache

    - name: Deploy Docker image
      run: docker push my-httpd-image
