name: Super Linter OpenAPI Lint

on:
  push:
    branches: [ test ]

jobs:
  super-linter:
    name: Super Linter OpenAPI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Super Linter
        uses: github/super-linter@v4
        with:
          lint-staged: false
          delete: false
          debug: false
          fail-fast: false
          mode: github-actions
      - name: Run Super Linter on OpenAPI specs
        run: |
          cd $GITHUB_WORKSPACE
          /usr/local/bin/super-linter --no-colors --json --log-level info --fail-on-warnings --validate-openapi
