name: Validate OpenAPI Spec

on:
  push:
    branches: [test]

jobs:
  openapi:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_CACHE: $rajesh9666544015/docker-image-cache

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Docker image
      uses: actions/cache@v2
      with:
        path: ${{ env.DOCKER_IMAGE_CACHE }}
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}

    - name: Pull Docker image
      if: steps.cache.outputs.cache-hit != 'true'
      run: docker pull github/super-linter:v4

    - name: Tag Docker image
      if: steps.cache.outputs.cache-hit != 'true'
      run: docker tag github/super-linter:v4 ${{ env.DOCKER_IMAGE_CACHE }}/github-super-linter:v4

    - name: Validate OpenAPI Spec
      uses: docker://$DOCKER_IMAGE_CACHE/github-super-linter:v4
      env:
        VALIDATE_OPENAPI: true
      with:
        commit_sha: ${{ github.sha }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: false
