on:
  workflow_dispatch:
  push:

jobs:
  Hello:
    runs-on: ubuntu-latest
    env:
      cache-name: my-cache-name  # Define cache-name environment variable
    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: |
            #/root/.cache
            #/root/.local/share/Super-Linter
            ${{ github.workspace }}/openapi
            #/root/.cache/Super-Linter
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Enterprise-API-Providers_Practitioner-1-swagger.yaml') }}

      - name: Checkout code
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

           
