name: SwaggerHub Integration
on: workflow_dispatch
jobs:
  Hello:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        id: lintcode
        env:
          VALIDATE_OPENAPI: true
          DEFAULT_BRANCH: swaggerhub
          CREATE_LOG_FILE: true
          LOG_FILE: linter.log
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List files
        id: lintOutput
        if: failure() && steps.lintcode.outcome == 'failure'
        run: |
          ERROR_REGEX='^.*:(.*)\serror\s.*$'
          grep -Eoh "$ERROR_REGEX" linter.log > aaa.log
          #grep "error" linter.log > error.log
          ls -a
          echo "::::::::::::::::::::::::::"
          cat linter.log
          echo "------------------------"
          echo "err-logs=$(cat aaa.log)" >> $GITHUB_OUTPUT
          #echo "${err-log}"
      - name: Extract errors
        id: log-extract
        if: failure() && steps.lintcode.outcome == 'failure'
        run: |
          ERROR_REGEX='^.*:(.*)\serror\s.*$'
          ERROR_FILE=$(grep -Eoh "$ERROR_REGEX" linter.log)
          ERROR_MESSAGE=$(grep -Eoh "$ERROR_REGEX" linter.log)
          echo "${ERROR_MESSAGE}"
          echo "error-logs=${ERROR_MESSAGE}" >> $GITHUB_OUTPUT
      - name: Print logs of previous step 
        if: failure() && steps.lintcode.outcome == 'failure'
        run: |
           echo  "${{ steps.lintOutput.outputs.err-logs }}"
      - name: External Api call (Weather Map)
        run: |
           HTTP_CODE=$(curl --write-out "%{http_code}\n" "https://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b6907d289e10d714a6e88b30761fae22" --output output.txt --silent)
      - name: Print External Api call Output 
        run: |
           echo $(cat output.txt)
