name: GitHub Super Linter
on:
  push:
    branches: [ test ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Super Linter
      run: |
        git clone https://github.com/github/super-linter.git /tmp/super-linter
        cd /tmp/super-linter
        ./install.sh
      env:
        VALIDATE_ALL_CODEBASE: true
    - name: Run Super Linter
      run: |
        /usr/bin/super-linter
      env:
        VALIDATE_ALL_CODEBASE: true
