name: My Docker Workflow


on:
  push:
    branches:
      - main

jobs:
  build-java-project:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - run: mkdir -p ~/linter-cache

        - id: linter-cache
          uses: actions/cache@v1
          with:
              path: ~/linter-cache
              key: linter-cache-${{ runner.os }}

        - if: steps.linter-cache.outputs.cache-hit != 'true'
          run: |
              echo "no cache"
              docker pull github/super-linter:v4
              docker save -o ~/linter-cache/super-linter.tar alpine

        - if: steps.linter-cache.outputs.cache-hit == 'true'
          run:  |
            echo "from cache"
            docker run -e RUN_LOCAL=true -e  VALIDATE_OPENAPI=true -v $PWD:/tmp/lint github/super-linter

