name: GitHub Super Linter
on:
  push:
    branches: [ test ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/super-linter
        key: ${{ runner.os }}-linter-${{ hashFiles('**/Enterprise-API-Providers_Practitioner-1-swagger.yaml') }}
        restore-keys: ${{ runner.os }}-linter-
    - name: GitHub Super Linter
      uses: github/super-linter@v4
      with:
        args: --no-test
      env:
        VALIDATE_ALL_CODEBASE: true
      working-directory: /tmp/super-linter
