name: Super Linter OpenAPI Lint

on:
  push:
    branches: [ test ]

jobs:
  super-linter:
    name: Super Linter OpenAPI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test
        run: |
          sudo ls -a
      - name: Lint Code Base
        #uses: docker://github/super-linter:v4
        uses: github/super-linter@v4
        env:
          VALIDATE_OPENAPI: true
