on:
  workflow_dispatch:
  push:
  
  
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: prathira
          password: dckr_pat_YC40q1ZsK_cLlxe5AXgSQSzKNK4
        
      
      - name: Pull Super Linter Docker image
        run: docker pull github/super-linter:v4
      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-Rajesh5
          restore-keys: ${{ runner.os }}-docker-Rajesh5
        env:
          cache-name: my-cache-name-dummy
      - name: Restore Super-Linter cache
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-Rajesh5
