name: SwaggerHub Integration
on: workflow_dispatch
jobs:
  Hello:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        id: lintcode
        env:
          VALIDATE_OPENAPI: true
          DEFAULT_BRANCH: swaggerhub
          CREATE_LOG_FILE: true
          LOG_FILE: linter.log
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List files
        id: lintOutput
        if: failure() && steps.lintcode.outcome == 'failure'
        run: |
          ERROR_REGEX='^.*:(.*)\serror\s.*$'
          grep -Eoh "$ERROR_REGEX" linter.log > error.log
          sed -i 's#"##g' error.log
          echo "#################################"
          echo $(cat error.log)
      - name: Update swagerHub
        if: failure() && steps.lintcode.outcome == 'failure'
        run: |
         curl -X 'POST' \
          'https://api.swaggerhub.com/apis/RAJESHP1231234_1/Rajesh/1.0.0/comments' \
           -H 'accept: application/json' \
           -H 'Authorization: 2f28cdbb-c5df-4146-a8c4-05046a380d00' \
            -H 'Content-Type: application/json' \
           -d '{
            "position": 0,
            "body": "echo $(cat error.log)"
          }'
