name: Validate OpenAPI Spec

on:
  push:
    branches: [test]

jobs:
  openapi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate OpenAPI Spec
      uses: github/super-linter@v4
      env:
        VALIDATE_OPENAPI: true
      with:
        commit_sha: ${{ github.sha }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: false

   
