name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello"
      - name: Print Bye
        run: echo "Bye"
      - name: Print gradle version
        run: gradle --version
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
           url: "http://google.com"
           method: GET
      - name: Show Response
        run: |
         echo ${{ steps.myRequest.outputs.response }}
         echo ${{ steps.myRequest.outputs.headers }}
      - name: Curl call
        id: curl
        run: |
          curl -X GET "https://gorest.co.in/public/v2/users"
      - name: Show Response
        run: |
         echo ${{ steps.curl.outputs.response }}
