name: OpenAPI Linting

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create directory for Super Linter dependencies
        run: mkdir -p /home/runner/.super-linter

      - name: Cache Super Linter dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/.super-linter
          key: ${{ runner.os }}-super-linter-${{ hashFiles('**/super-linter.json') }}
          restore-keys: |
            ${{ runner.os }}-super-linter-

      - name: Install dependencies
        run: |
          cd /home/runner/.super-linter
          npm install

      - name: Lint OpenAPI spec
        uses: github/super-linter@v4
        with:
          args: openapi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
