name: OpenAPI Linting

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint OpenAPI spec
        uses: github/super-linter/slim@v4
        with:
          args: openapi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
