name: Docker Image Download and Cache

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Cache httpd Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=registry,ref=httpd:latest
          cache-to: type=inline
          push: false
          target: development
          file: ./Dockerfile

      - name: Build and Run Container
        run: |
          docker build -t my-httpd-image .
          docker run -d -p 80:80 my-httpd-image
