name: Super Linter
on: [push, pull_request]
jobs:
  super-linter:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_OPENAPI: true
        VALIDATE_DOCKERFILE: false
        VALIDATE_TERRAFORM: false
        VALIDATE_ARM: false
        VALIDATE_CFN: false
        VALIDATE_GIT_COMMIT_MSG: false
        VALIDATE_MAKEFILE: false
        VALIDATE_MARKDOWN_LINK_CHECK: false
        OPENAPI_PATHS: "openapi/**/*.yaml, openapi/**/*.yml"

