on:
  workflow_dispatch:
  push:

jobs:
  Hello:
    runs-on: ubuntu-latest
    env:
      cache-name: my-cache-name  # Define cache-name environment variable
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test
        run: |
          ls /root/.cache
          echo ":::::::::::::::"
          ls /root/.local/share/Super-Linter
          echo "----------------------"
          ls /root/.cache/Super-Linter

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: |
            #/root/.cache
            #/root/.local/share/Super-Linter
            /root/.cache/Super-Linter
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Enterprise-API-Providers_Practitioner-1-swagger.yaml') }}
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        id: lintcode
        env:
          VALIDATE_OPENAPI: true
          DEFAULT_BRANCH: main
          CREATE_LOG_FILE: true
          LOG_FILE: linter.log
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPER_LINTER_USE_CACHE: true
          SUPER_LINTER_CACHE_PATH: /root/.cache/Super-Linter
