name: My Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Docker Image
        id: cache-docker-image
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-httpd
          restore-keys: ${{ runner.os }}-docker-

      - name: Pull Docker Image
        run: docker pull httpd

      - name: Deploy Docker Image
        run: |
          docker stop my-container || true
          docker rm my-container || true
          docker run -d --name my-container -p 80:80 httpd
