name: Super Linter

on:
  push:

jobs:
  super-linter:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache dependencies
      if: failure()
      uses: actions/cache@v2
      with:
        # A unique key to identify the cache
        # based on the operating system, node version, and other dependencies
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        # The path to the node_modules directory to cache
        path: ~/.npm
        # Cache all files under node_modules
        # except those listed in .gitignore or .npmignore
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Lint code
      uses: github/super-linter@v4
      with:
        # Optional: set a custom configuration file
        configuration-file: .github/linters/.openapirc.yml
        # Required: set the list of linters to run
        # and their configuration (if any)
        # In this case, we are running the OpenAPI linter
        # and pointing it to the OpenAPI spec file in the repository
        linters: |
          openapi:
            enabled: true
            config:
              openapi_path: openapi/Enterprise-API-Providers_Practitioner-1-swagger.yaml
