name: Lint OpenAPI spec

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Super Linter checkout code
      uses: actions/cache@v2
      with:
        path: ~/.super-linter
        key: super-linter-checkout
        restore-keys: |
          super-linter-checkout-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y npm
        npm install -g @stoplight/spectral

    - name: Lint OpenAPI spec
      uses: github/super-linter@v4
