name: GitHub Super Linter
on:
  push:
    branches: [ test ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/super-linter
        key: ${{ runner.os }}-linter-${{ hashFiles('**/super-linter.config.yml') }}
        restore-keys: ${{ runner.os }}-linter-
    - name: GitHub Super Linter
      uses: github/super-linter@v4
      with:
        args: --no-test
      env:
        VALIDATE_ALL_CODEBASE: true
      run: |
        cd /tmp/super-linter
        super-linter
