name: GitHub Super Linter
on:
  push:
    branches: [ test ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Super Linter
      run: |
        npm install -g super-linter
      env:
        VALIDATE_ALL_CODEBASE: true
    - name: Run Super Linter
      run: |
        /usr/bin/super-linter
      env:
        VALIDATE_ALL_CODEBASE: true
