on:
  workflow_dispatch:
  push:

jobs:
  Hello:
    runs-on: ubuntu-latest
    env:
      cache-name: my-cache-name  # Define cache-name environment variable
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: prathira
          password: dckr_pat_YC40q1ZsK_cLlxe5AXgSQSzKNK4
      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-Rajesh
          restore-keys: ${{ runner.os }}-docker-Rajesh
      - name: Pull Super Linter Docker image
        run: docker pull github/super-linter:v4
