name: SwaggerHub Integration

on:
  workflow_dispatch:
  push:

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: prathira
          password: dckr_pat_NC9nyfU_o-9QwRQRud2JDXv3agI

      - name: Lint Code Base
        run: |
          docker run -e RUN_LOCAL=true -e VALIDATE_OPENAPI=true --rm -v "$(pwd):/tmp/lint" prathira/super-linter:93
