name: Lint

on:
  push:
    branches: [ test ]
  pull_request:

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-super-linter .
      - name: Super lint OpenAPI specification
        run: |
          docker run --rm -v "$(pwd)":/tmp/workspace -v /tmp/cache:/tmp/cache my-super-linter

