name: Super Linter OpenAPI Lint

on:
  push:
    branches: [ test ]

jobs:
  super-linter:
    name: Super Linter OpenAPI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_OPENAPI: true
