name: lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/bin/docker
            /path/to/cache/dir/super-linter.tar.gz
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Load Docker image
        run: |
          gzip -d /path/to/cache/dir/super-linter.tar.gz | docker load

      - name: Run Super Linter
        run: |
          docker run --rm ghcr.io/github/super-linter
