name: Super-Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Docker Layer Caching
        uses: docker/setup-buildx-action@v1

      - name: Pull Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          cache-from: type=registry,ref=github/super-linter:latest
          cache-to: type=inline
          target: mytarget

      - name: Run Super-Linter
        run: docker run --rm -v $(pwd):/tmp/lint github/super-linter

