name: My Docker Workflow


on:
  push:
    branches:
      - main

jobs:
  build-java-project:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - run: |
             docker build -t temp-linter .
             docker images
        

        
