name: Create Secrets and Environment Variables

on:
  push:
    branches: [ main ]

jobs:
  create-secrets-and-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Create Secret
        uses: actions/secrets-set@v2
        with:
          name: MY_SECRET_NAME
          value: ${{ secrets.MY_SECRET_VALUE }}

      - name: Create Environment Variable
        run: echo "MY_ENVIRONMENT_VARIABLE_NAME=$MY_ENVIRONMENT_VARIABLE_VALUE" >> $GITHUB_ENV
        env:
          MY_ENVIRONMENT_VARIABLE_NAME: my-value
