name: My Workflow


on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Docker image
      run: docker pull github/super-linter:slim-v5

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-
    - name: Change permissions of Docker files and directories
      run: |
        sudo chown -R $USER /var/lib/docker
        sudo chmod -R 777 /var/lib/docker
